name: Build and Deploy

# Trigger the workflow on push to specific branches
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:    

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK for Java build
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build using Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Upload the build artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: application-jar
          path: target/*.jar

  deploy:
    name: Deploy to Kubernetes
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code (optional if Kubernetes manifests are in repo)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Download the build artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: application-jar
          path: target/

      # Step 3: Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      # Step 4: Configure Kubernetes cluster (using Kubeconfig)
      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          kubectl config get-contexts

      # Step 5: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout status deployment/provisioning-service
